# Generated by Django 4.2.7 on 2024-02-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Desconto', 'verbose_name_plural': 'Descontos'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_depth',
            new_name='product_lenght',
        ),
    ]
