# Generated by Django 4.2.7 on 2024-02-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_lenght',
            new_name='product_length',
        ),
    ]
