# Generated by Django 4.2.7 on 2024-02-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_product_lenght_product_product_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Peso bruto (em Kg):'),
        ),
    ]
