# Generated by Django 4.2.7 on 2024-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(verbose_name='Disponível'),
        ),
    ]
