# Generated by Django 4.2.7 on 2024-02-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=30, verbose_name='Inscrito')),
                ('subscriber_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
