# Generated by Django 4.2.7 on 2024-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
