# Generated by Django 4.2.7 on 2024-02-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['subscriber_name'], 'verbose_name': 'Inscrito', 'verbose_name_plural': 'Inscritos'},
        ),
    ]
