# Generated by Django 4.2.7 on 2024-01-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_breve',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
