# Generated by Django 4.2.7 on 2024-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_category_breve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_breve',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Descrição breve'),
        ),
    ]
