# Generated by Django 4.2.7 on 2024-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_evaluation_delete_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_office_cep',
            field=models.CharField(max_length=11, verbose_name='CEP do escritório'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_store_cep',
            field=models.CharField(max_length=11, verbose_name='CEP da loja'),
        ),
    ]
