# Generated by Django 4.2.7 on 2024-04-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountorder',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_method',
            field=models.CharField(default='ttt', max_length=15),
            preserve_default=False,
        ),
    ]
