# Generated by Django 4.2.7 on 2024-04-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_discountorder_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_cpf',
            field=models.CharField(default=111, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=30)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('data_netrega', models.DateField()),
                ('codigo_entrega', models.CharField(blank=True, max_length=30, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
