# Generated by Django 4.2.7 on 2024-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer_customer_cpf_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='codigo_entrega',
            new_name='codigo_rastreio',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='data_netrega',
        ),
        migrations.AddField(
            model_name='delivery',
            name='data_entrega',
            field=models.DateField(null=True),
        ),
    ]
